---
# file: tasks/install-blackbox-exporter.yml
#
# Install Prometheus blackbox-exporter.
#
# @see http://prometheus.io/docs/introduction/getting_started/
#

- name: Check if blackbox_exporter already installed...
  stat:
    path: '{{ prometheus_install_path }}/blackbox_exporter-{{ prometheus_blackbox_exporter_version }}.{{ prometheus_platform_suffix }}/blackbox_exporter'
  register: blackbox_exporter_stat

- block:

    - name: set internal variables for convenience
      set_fact:
        prometheus_blackbox_exporter_subdir: "{{ prometheus_install_path }}/blackbox_exporter-{{ prometheus_blackbox_exporter_version }}.{{ prometheus_platform_suffix }}"


    - name: set download url for versions >= 0.2.0
      set_fact:
        prometheus_blackbox_exporter_tarball_url: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ prometheus_blackbox_exporter_version }}/blackbox_exporter-{{ prometheus_blackbox_exporter_version }}.{{ prometheus_platform_suffix }}.tar.gz"
      when: prometheus_blackbox_exporter_version | version_compare('0.2.0', '>=')

    - name: set download url for versions < 0.2.0 (OBSOLETE!)
      set_fact:
        prometheus_blackbox_exporter_tarball_url: "https://github.com/prometheus/blackbox_exporter/releases/download/{{ prometheus_blackbox_exporter_version }}/blackbox_exporter-{{ prometheus_blackbox_exporter_version }}.{{ prometheus_platform_suffix }}.tar.gz"
      when: prometheus_blackbox_exporter_version | version_compare('0.2.0', '<')

    - name: set daemon dir for versions >= 0.2
      set_fact:
        prometheus_blackbox_exporter_daemon_dir: "{{ prometheus_blackbox_exporter_subdir }}"
      when: prometheus_blackbox_exporter_version | version_compare('0.2', '>=')

    - name: set daemon dir for versions < 0.2 (OBSOLETE!)
      set_fact:
        prometheus_blackbox_exporter_daemon_dir: "{{ prometheus_install_path }}"
      when: prometheus_blackbox_exporter_version | version_compare('0.2', '<')

    - name: download and untar blackbox_exporter tarball
      unarchive:
        src: "{{ prometheus_blackbox_exporter_tarball_url }}"
        dest: "{{ prometheus_install_path }}"
        copy: no
      when: blackbox_exporter_stat.stat.exists == False
  when: prometheus_blackbox_exporter_version != "git"


- block:

    - name: set internal variables for convenience
      set_fact:
        prometheus_blackbox_exporter_git_url: "https://github.com/prometheus/blackbox_exporter.git"
        prometheus_blackbox_exporter_src_path: "{{ prometheus_goroot }}/src/github.com/prometheus/blackbox_exporter"
        prometheus_blackbox_exporter_daemon_dir: "{{ prometheus_install_path }}"

    - name: delete the blackbox_exporter build directory, if necessary
      file: path={{ prometheus_blackbox_exporter_src_path }}  state=absent
      when: prometheus_rebuild

    - name: mkdir for blackbox_exporter source code
      file: path={{ prometheus_blackbox_exporter_src_path }}  state=directory

    - name: clone the blackbox_exporter project src
      git:
        repo: "{{ prometheus_blackbox_exporter_git_url }}"
        dest: "{{ prometheus_blackbox_exporter_src_path }}"
        force: yes

    - name: build blackbox_exporter source code
      command: make
      args:
        chdir: "{{ prometheus_blackbox_exporter_src_path }}"
        creates: blackbox_exporter
      environment:
        GO15VENDOREXPERIMENT: 1
        GOROOT: "{{ prometheus_goroot }}"
        GOPATH: "{{ prometheus_gopath }}"
        PATH: "{{ ansible_env.PATH }}:{{ prometheus_goroot }}/bin:{{ prometheus_gopath }}/bin"

    - name: copy the built blackbox_exporter to the install path
      command: "cp {{ prometheus_blackbox_exporter_src_path }}/blackbox_exporter {{ prometheus_install_path }}"
      args:
        creates: "{{ prometheus_install_path }}/blackbox_exporter"

  when: prometheus_blackbox_exporter_version == "git"



- name: set permissions, owner and group
  file: path={{ prometheus_blackbox_exporter_daemon_dir }}/blackbox_exporter owner={{ prometheus_user }} group={{ prometheus_group }} mode="go-w"

- name: mkdir for data
  file:
    path: "{{ prometheus_db_path }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "u=rwx,g=rx,o="

- name: set blackbox_exporter variables
  copy: src="../files/etc-default-blackbox_exporter"  dest=/etc/default/blackbox_exporter
  register: blackbox_exporter_config

- debug: var=blackbox_exporter_config
  notify: reload blackbox_exporter
  when: blackbox_exporter_config.changed


- name: copy INIT script to server
  template: src="../templates/blackbox_exporter.sysvinit.{{ ansible_os_family|lower }}.sh.j2"  dest="/etc/init.d/blackbox_exporter"  mode="a+x"
  when: not prometheus_blackbox_exporter_use_systemd|bool

- name: copy systemd config to server
  template: src="../templates/blackbox_exporter.service.j2"  dest="/lib/systemd/system/blackbox_exporter.service"
  when: prometheus_blackbox_exporter_use_systemd|bool


- name: set INIT status and start
  service: name=blackbox_exporter enabled=yes state=started

- name: install blackbox config file from playbook's, if any
  template: src="{{ playbook_dir }}/{{ prometheus_blackbox_conf }}"  dest="{{ prometheus_config_path }}/blackbox.yml"
  when: prometheus_blackbox_conf is defined
  notify:
    - restart blackbox_exporter

- name: install default (empty) blackbox config file, if necessary
  copy: src="../files/blackbox.empty.yml"  dest="{{ prometheus_config_path }}/blackbox.yml"
  when: prometheus_blackbox_conf is not defined
  notify:
    - restart blackbox_exporter
