---
# file: tasks/install-blackbox-exporter.yml
#
# Install Prometheus blackbox-exporter.
#
# @see http://prometheus.io/docs/introduction/getting_started/
#

- name: Check if blackbox_exporter already installed...
  stat:
    path: '{{ prometheus_install_path }}/blackbox_exporter-{{ prometheus_blackbox_exporter_version }}.{{ prometheus_platform_suffix }}/blackbox_exporter'
  register: blackbox_exporter_stat

- block:

    - name: set internal variables for convenience
      set_fact:
        prometheus_blackbox_exporter_subdir: "{{ prometheus_install_path }}/blackbox_exporter-{{ prometheus_blackbox_exporter_version }}.{{ prometheus_platform_suffix }}"


    - name: set download url for versions >= 0.2.0
      set_fact:
        prometheus_blackbox_exporter_tarball_url: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ prometheus_blackbox_exporter_version }}/blackbox_exporter-{{ prometheus_blackbox_exporter_version }}.{{ prometheus_platform_suffix }}.tar.gz"
      when: prometheus_blackbox_exporter_version | version_compare('0.2.0', '>=')

    - name: set download url for versions < 0.2.0 (OBSOLETE!)
      set_fact:
        prometheus_blackbox_exporter_tarball_url: "https://github.com/prometheus/blackbox_exporter/releases/download/{{ prometheus_blackbox_exporter_version }}/blackbox_exporter-{{ prometheus_blackbox_exporter_version }}.{{ prometheus_platform_suffix }}.tar.gz"
      when: prometheus_blackbox_exporter_version | version_compare('0.2.0', '<')

    - name: set daemon dir for versions >= 0.2
      set_fact:
        prometheus_blackbox_exporter_daemon_dir: "{{ prometheus_blackbox_exporter_subdir }}"
      when: prometheus_blackbox_exporter_version | version_compare('0.2', '>=')

    - name: set daemon dir for versions < 0.2 (OBSOLETE!)
      set_fact:
        prometheus_blackbox_exporter_daemon_dir: "{{ prometheus_install_path }}"
      when: prometheus_blackbox_exporter_version | version_compare('0.2', '<')

    - name: download and untar blackbox_exporter tarball
      unarchive:
        src: "{{ prometheus_blackbox_exporter_tarball_url }}"
        dest: "{{ prometheus_install_path }}"
        remote_src: yes
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
      when: blackbox_exporter_stat.stat.exists == False
  when: prometheus_blackbox_exporter_version != "git"


- name: set permissions, owner and group
  file: path={{ prometheus_blackbox_exporter_daemon_dir }}/blackbox_exporter owner={{ prometheus_user }} group={{ prometheus_group }} mode="go-w"

- name: mkdir for data
  file:
    path: "{{ prometheus_db_path }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "u=rwx,g=rx,o="

- name: set blackbox_exporter variables
  copy: src="../files/etc-default-blackbox_exporter"  dest=/etc/default/blackbox_exporter
  register: blackbox_exporter_config

- debug: var=blackbox_exporter_config
  notify: reload blackbox_exporter
  when: blackbox_exporter_config.changed


- name: copy INIT script to server
  template: src="../templates/blackbox_exporter.sysvinit.{{ ansible_os_family|lower }}.sh.j2"  dest="/etc/init.d/blackbox_exporter"  mode="a+x"
  when: ansible_service_mgr != "systemd"
  notify:
    - restart blackbox_exporter

- name: copy systemd config to server
  template: src="../templates/blackbox_exporter.service.j2"  dest="/lib/systemd/system/blackbox_exporter.service"
  when: ansible_service_mgr == "systemd"
  notify:
    - restart blackbox_exporter

- name: install blackbox config file from playbook's, if any
  template: src="{{ playbook_dir }}/{{ prometheus_blackbox_conf }}"  dest="{{ prometheus_config_path }}/blackbox.yml"
  when: prometheus_blackbox_conf is defined
  notify:
    - restart blackbox_exporter

- name: install default (empty) blackbox config file, if necessary
  copy: src="../files/blackbox.empty.yml"  dest="{{ prometheus_config_path }}/blackbox.yml"
  when: prometheus_blackbox_conf is not defined
  notify:
    - restart blackbox_exporter
