---
# file: handlers/main.yml
#

- name: restart prometheus
  service: name=prometheus state=restarted
  when: prometheus_use_service|bool

- name: reload prometheus
  service: name=prometheus state=reloaded
  when: prometheus_use_service|bool

- name: stop prometheus
  service: name=prometheus state=stopped
  when: prometheus_use_service|bool



- name: restart node_exporter
  service: name=node_exporter state=restarted

- name: reload node_exporter
  service: name=node_exporter state=reloaded

- name: stop node_exporter
  service: name=node_exporter state=stopped

- name: restart blackbox_exporter
  service: name=blackbox_exporter state=restarted

- name: reload blackbox_exporter
  service: name=blackbox_exporter state=reloaded

- name: stop blackbox_exporter
  service: name=blackbox_exporter state=stopped


- name: restart alertmanager
  service: name=alertmanager state=restarted
  when: prometheus_use_service|bool

- name: reload alertmanager
  service: name=alertmanager state=reloaded
  when: prometheus_use_service|bool

- name: stop alertmanager
  service: name=alertmanager state=stopped
  when: prometheus_use_service|bool

- name: restart nginx_vts_exporter
  service: name=nginx_vts_exporter state=restarted

- name: reload nginx_vts_exporter
  service: name=nginx_vts_exporter state=reloaded

- name: stop nginx_vts_exporter
  service: name=nginx_vts_exporter state=stopped
