---
# file: handlers/main.yml
#

- name: restart prometheus
  service: name=prometheus state=restarted

- name: reload prometheus
  service: name=prometheus state=reloaded

- name: stop prometheus
  service: name=prometheus state=stopped

- name: restart alertmanager
  service: name=alertmanager state=restarted

- name: reload alertmanager
  service: name=alertmanager state=reloaded

- name: stop alertmanager
  service: name=alertmanager state=stopped

- name: restart node_exporter
  service: name=node_exporter state=restarted

- name: reload node_exporter
  service: name=node_exporter state=reloaded

- name: stop node_exporter
  service: name=node_exporter state=stopped

- name: restart blackbox_exporter
  service: name=blackbox_exporter state=restarted

- name: reload blackbox_exporter
  service: name=blackbox_exporter state=reloaded

- name: stop blackbox_exporter
  service: name=blackbox_exporter state=stopped

- name: restart nginx_vts_exporter
  service: name=nginx_vts_exporter state=restarted

- name: reload nginx_vts_exporter
  service: name=nginx_vts_exporter state=reloaded

- name: stop nginx_vts_exporter
  service: name=nginx_vts_exporter state=stopped

- name: restart redis_exporter
  service: name=redis_exporter state=restarted

- name: reload redis_exporter
  service: name=redis_exporter state=reloaded

- name: stop redis_exporter
  service: name=redis_exporter state=stopped

- name: restart postgres_exporter
  service: name=postgres_exporter state=restarted

- name: reload postgres_exporter
  service: name=postgres_exporter state=reloaded

- name: stop postgres_exporter
  service: name=postgres_exporter state=stopped

- name: restart mysqld_exporter
  service: name=mysqld_exporter state=restarted

- name: reload mysqld_exporter
  service: name=mysqld_exporter state=reloaded

- name: stop mysqld_exporter
  service: name=mysqld_exporter state=stopped

- name: restart hpraid_exporter
  service: name=hpraid_exporter state=restarted

- name: reload hpraid_exporter
  service: name=hpraid_exporter state=reloaded

- name: stop hpraid_exporter
  service: name=hpraid_exporter state=stopped

- name: restart process_exporter
  service: name=process_exporter state=restarted

- name: reload process_exporter
  service: name=process_exporter state=reloaded

- name: stop process_exporter
  service: name=process_exporter state=stopped
